"use client";

import * as React from "react";
import { Bell, Check, Loader2 } from "lucide-react";
import { useRouter, usePathname } from "next/navigation";
import * as Popover from "@/components/ui/popover";
import { cn } from "@/lib/utils/utils";

interface NotificationItem {
  id: string;
  type: string;
  title: string;
  message: string;
  entityType?: string | null;
  entityId?: string | null;
  read: boolean;
  createdAt: string;
}

interface NotificationsResponse {
  notifications: NotificationItem[];
  total: number;
  unreadCount: number;
}

// Map a notification's entityType to its in-app destination. Mirrors the
// base paths used by components/shared/entity-link.tsx so deep-links stay
// consistent with the rest of the app.
const ENTITY_BASE_PATH: Record<string, string> = {
  Property: "/portfolio",
  Tenant: "/people",
  Lease: "/leases",
  Invoice: "/financials",
  Payment: "/financials",
  Receipt: "/financials",
  Maintenance: "/maintenance",
  Document: "/documents",
};

function formatRelative(iso: string): string {
  const then = new Date(iso).getTime();
  if (Number.isNaN(then)) return "";
  const diff = Date.now() - then;
  const mins = Math.round(diff / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.round(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.round(hours / 24);
  return `${days}d ago`;
}

/**
 * In-app notification center. Surfaces the notifications already generated by
 * the server-side automation (rent reminders, overdue notices, lease renewals,
 * receipt deadlines) via GET /api/notifications, with an unread badge,
 * mark-all-read, and per-item deep-linking to the related entity.
 */
export function NotificationBell({ className }: { className?: string }): React.ReactElement {
  const router = useRouter();
  const pathname = usePathname();
  const locale = pathname.split("/")[1] || "pt";

  const [open, setOpen] = React.useState(false);
  const [items, setItems] = React.useState<NotificationItem[]>([]);
  const [unread, setUnread] = React.useState(0);
  const [loading, setLoading] = React.useState(false);

  const fetchNotifications = React.useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/notifications?limit=12", { cache: "no-store" });
      if (!res.ok) return;
      const data: NotificationsResponse | NotificationItem[] = await res.json();
      // The API returns an array in mock mode and an object otherwise.
      const list = Array.isArray(data) ? data : data.notifications;
      const unreadCount = Array.isArray(data)
        ? data.filter((n) => !n.read).length
        : data.unreadCount;
      setItems(list ?? []);
      setUnread(unreadCount ?? 0);
    } catch {
      // Network hiccup — leave the last known state in place.
    } finally {
      setLoading(false);
    }
  }, []);

  // Initial load + light polling so the badge stays roughly live without
  // requiring websockets. Cheap: one small request per minute.
  React.useEffect(() => {
    void fetchNotifications();
    const id = window.setInterval(() => void fetchNotifications(), 60_000);
    return () => window.clearInterval(id);
  }, [fetchNotifications]);

  // Refetch when the panel is opened so counts reflect reality on demand.
  React.useEffect(() => {
    if (open) void fetchNotifications();
  }, [open, fetchNotifications]);

  const markAllRead = React.useCallback(async () => {
    setUnread(0);
    setItems((prev) => prev.map((n) => ({ ...n, read: true })));
    try {
      await fetch("/api/notifications/mark-all-read", { method: "PUT" });
    } catch {
      void fetchNotifications();
    }
  }, [fetchNotifications]);

  const handleItemClick = React.useCallback(
    async (item: NotificationItem) => {
      setOpen(false);
      if (!item.read) {
        setItems((prev) => prev.map((n) => (n.id === item.id ? { ...n, read: true } : n)));
        setUnread((u) => Math.max(0, u - 1));
        try {
          await fetch(`/api/notifications/${item.id}`, {
            method: "PUT",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ read: true }),
          });
        } catch {
          /* best effort */
        }
      }
      const base = item.entityType ? ENTITY_BASE_PATH[item.entityType] : undefined;
      const href = base
        ? `/${locale}${base}${item.entityId ? `/${item.entityId}` : ""}`
        : `/${locale}/dashboard`;
      router.push(href);
    },
    [locale, router],
  );

  return (
    <Popover.Root open={open} onOpenChange={setOpen}>
      <Popover.Trigger
        className={cn(
          "relative inline-flex items-center justify-center h-8 w-8 rounded-md",
          "text-[var(--color-muted-foreground)] hover:bg-[var(--color-hover)] hover:text-[var(--color-foreground)]",
          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-focus)]",
          className,
        )}
        aria-label={unread > 0 ? `Notifications, ${unread} unread` : "Notifications"}
      >
        <Bell className="h-4 w-4" aria-hidden="true" />
        {unread > 0 && (
          <span
            className="absolute -top-0.5 -right-0.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-[var(--color-error)] px-1 text-[10px] font-semibold leading-none text-white"
            aria-hidden="true"
          >
            {unread > 9 ? "9+" : unread}
          </span>
        )}
      </Popover.Trigger>

      <Popover.Content align="end" sideOffset={8} className="w-80 p-0 overflow-hidden">
        <div className="flex items-center justify-between border-b border-[var(--color-border)] px-4 py-3">
          <p className="text-sm font-semibold text-[var(--color-foreground)]">Notifications</p>
          {unread > 0 && (
            <button
              type="button"
              onClick={markAllRead}
              className="inline-flex items-center gap-1 text-xs font-medium text-[var(--color-primary)] hover:underline"
            >
              <Check className="h-3.5 w-3.5" /> Mark all read
            </button>
          )}
        </div>

        <div className="max-h-[60vh] overflow-y-auto">
          {loading && items.length === 0 ? (
            <div className="flex items-center justify-center py-10 text-[var(--color-muted-foreground)]">
              <Loader2 className="h-5 w-5 animate-spin" />
            </div>
          ) : items.length === 0 ? (
            <div className="px-4 py-10 text-center">
              <Bell className="mx-auto h-6 w-6 text-[var(--color-muted-foreground)]" />
              <p className="mt-2 text-sm text-[var(--color-muted-foreground)]">
                You&apos;re all caught up
              </p>
            </div>
          ) : (
            <ul className="divide-y divide-[var(--color-border)]">
              {items.map((item) => (
                <li key={item.id}>
                  <button
                    type="button"
                    onClick={() => handleItemClick(item)}
                    className={cn(
                      "flex w-full items-start gap-3 px-4 py-3 text-left transition-colors hover:bg-[var(--color-hover)]",
                      !item.read && "bg-[var(--color-primary)]/5",
                    )}
                  >
                    <span
                      className={cn(
                        "mt-1.5 h-2 w-2 shrink-0 rounded-full",
                        item.read ? "bg-transparent" : "bg-[var(--color-primary)]",
                      )}
                      aria-hidden="true"
                    />
                    <span className="min-w-0 flex-1">
                      <span className="block truncate text-sm font-medium text-[var(--color-foreground)]">
                        {item.title}
                      </span>
                      <span className="mt-0.5 block line-clamp-2 text-xs text-[var(--color-muted-foreground)]">
                        {item.message}
                      </span>
                      <span className="mt-1 block text-[10px] uppercase tracking-wide text-[var(--color-muted-foreground)]">
                        {formatRelative(item.createdAt)}
                      </span>
                    </span>
                  </button>
                </li>
              ))}
            </ul>
          )}
        </div>
      </Popover.Content>
    </Popover.Root>
  );
}

export default NotificationBell;
