// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config"; // Removed for production compatibility
import { defineConfig } from "prisma/config";

const schemaPath = "prisma/schema.prisma";

const defaultUrl =
  process.env["NODE_ENV"] === "production"
    ? "postgresql://proman:proman@localhost:5432/proman"
    : "postgresql://proman:proman@localhost:5432/proman_dev";

export default defineConfig({
  schema: schemaPath,
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || defaultUrl,
  },
});
